/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    kotlin("jvm")
    id("java")
    id("com.diffplug.spotless")
}

group = "net.yewton.asobiba"

kotlin {
    jvmToolchain(17)
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation(platform("net.yewton.asobiba.platform:product-platform"))
    testImplementation(platform("net.yewton.asobiba.platform:test-platform"))

    // Use the Kotlin JDK 8 standard library.
    implementation(kotlin("stdlib-jdk8"))
    implementation("org.jetbrains:annotations")

    testImplementation("io.kotest:kotest-assertions-core")
    testImplementation("io.kotest:kotest-runner-junit5")
}

tasks.test {
    useJUnitPlatform()
}

testing {
    suites {
        // Configure the built-in test suite
        getting(JvmTestSuite::class) {
            // Use JUnit Jupiter test framework
            useJUnitJupiter()
        }
    }
}

spotless {
    encoding("UTF-8")
    pluginManager.withPlugin("java") {
        java {
            importOrder()
            removeUnusedImports()
            googleJavaFormat()
            targetExclude("build/generated/**/*.java")
        }
    }

    pluginManager.withPlugin("org.jetbrains.kotlin.jvm") {
        kotlin {
            diktat().configFile("${rootDir}/../diktat-analysis.yml")
        }
        kotlinGradle {
            diktat().configFile("${rootDir}/../diktat-analysis.yml")
        }
    }
}

