services:
  db:
    image: postgres:15.4@sha256:d9b1b0ec74e734772a2e76c72d36a51de21f3842a6c872cf356a26a0a6b903d2
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: asobiba
    ports:
      - '15432:5432'
  db2:
    image: mariadb:11.1.2@sha256:77e8ad8ae65e4bf59da8e0c078a086fce71a5cff21ae3c72e55573f3fde33580
    volumes:
      - db2-data:/var/lib/mysql
    environment:
      MARIADB_USER: maria
      MARIADB_PASSWORD: my_cool_secret
      MARIADB_ROOT_PASSWORD: my-secret-pw
      MARIADB_DATABASE: asobiba
    ports:
      - '13306:3306'

  redis:
    image: redis:7.2.1@sha256:f92a0be0ba8c085e6a5e2d2bea386365443485bcd67ced5ca8ddcdacdd4656d2
    ports:
      - '16379:6379'
  zipkin:
    image: openzipkin/zipkin-slim@sha256:929ef4ba52188f342716a6407b1a4537013fd7b1814ab7cde9f56ef5cc22f5f0
    ports:
      - 9411:9411

volumes:
  db-data:
  db2-data:
