services:
  db:
    image: postgres:15.1
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: asobiba
    ports:
      - '15432:5432'
  redis:
    image: redis:7.0.8
    ports:
      - '16379:6379'

volumes:
  db-data:
