services:
  db:
    image: postgres:16.1@sha256:49c276fa02e3d61bd9b8db81dfb4784fe814f50f778dce5980a03817438293e3
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: asobiba
    ports:
      - '15432:5432'
  db2:
    image: mariadb:11.2.2@sha256:02c68e5ce1010eccd7db21b3c8bd47d1654dd853be5fbc4fe29adf31158b9a78
    volumes:
      - db2-data:/var/lib/mysql
    environment:
      MARIADB_USER: maria
      MARIADB_PASSWORD: my_cool_secret
      MARIADB_ROOT_PASSWORD: my-secret-pw
      MARIADB_DATABASE: asobiba
    ports:
      - '13306:3306'

  redis:
    image: redis:7.2.4@sha256:b5ddcd52d425a8e354696c022f392fe45fca928f68d6289e6bb4a709c3a74668
    ports:
      - '16379:6379'
  zipkin:
    image: openzipkin/zipkin-slim@sha256:7547e52aad2eb4c015607c2132e4b55f5ac56db637eb3233348e22f9922372bf
    ports:
      - 9411:9411

volumes:
  db-data:
  db2-data:
