services:
  db:
    image: postgres:15.1
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: asobiba
    ports:
      - '15432:5432'
  db2:
    image: mariadb:10.11.2
    volumes:
      - db2-data:/var/lib/mysql
    environment:
      MARIADB_USER: maria
      MARIADB_PASSWORD: my_cool_secret
      MARIADB_ROOT_PASSWORD: my-secret-pw
      MARIADB_DATABASE: asobiba
    ports:
      - '13306:3306'

  redis:
    image: redis:7.0.8
    ports:
      - '16379:6379'

volumes:
  db-data:
  db2-data:
