services:
  db:
    image: postgres:16.1@sha256:09f23e02d76670d3b346a3c00aa33a27cf57aab8341eedfcdaed41459d14f5c4
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: asobiba
    ports:
      - '15432:5432'
  db2:
    image: mariadb:11.2.3@sha256:0f0a49c44b7603ccc35c2828be9ce9febb3ef0cf5975ba7ecfabb3a3ec4cdcdb
    volumes:
      - db2-data:/var/lib/mysql
    environment:
      MARIADB_USER: maria
      MARIADB_PASSWORD: my_cool_secret
      MARIADB_ROOT_PASSWORD: my-secret-pw
      MARIADB_DATABASE: asobiba
    ports:
      - '13306:3306'

  redis:
    image: redis:7.2.4@sha256:e647cfe134bf5e8e74e620f66346f93418acfc240b71dd85640325cb7cd01402
    ports:
      - '16379:6379'
  zipkin:
    image: openzipkin/zipkin-slim@sha256:69bf9b98696a3aa18480cfbf5c9929c1663c668b9c9190ffda6c1c66465ab789
    ports:
      - 9411:9411

volumes:
  db-data:
  db2-data:
