services:
  db:
    image: postgres:16.3@sha256:d0f363f8366fbc3f52d172c6e76bc27151c3d643b870e1062b4e8bfe65baf609
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: asobiba
    ports:
      - '15432:5432'
  db2:
    image: mariadb:11.5.2@sha256:528a1cb190a336ee9f5d2ee39a26eac3c50a237c4cfbfabd65e29bbce18138b9
    volumes:
      - db2-data:/var/lib/mysql
    environment:
      MARIADB_USER: maria
      MARIADB_PASSWORD: my_cool_secret
      MARIADB_ROOT_PASSWORD: my-secret-pw
      MARIADB_DATABASE: asobiba
    ports:
      - '13306:3306'

  redis:
    image: redis:7.4.1@sha256:541209804a009ab69e97a06504706cfe83be2693150885fa08ed05a91f243089
    ports:
      - '16379:6379'
  zipkin:
    image: openzipkin/zipkin-slim@sha256:edc6a19af56b41f802ae5367a17c9659a97115426801fa22a67306c69e20433e
    ports:
      - 9411:9411

volumes:
  db-data:
  db2-data:
