services:
  db:
    image: postgres:17.0@sha256:8d3be35b184e70d81e54cbcbd3df3c0b47f37d06482c0dd1c140db5dbcc6a808
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: asobiba
    ports:
      - '15432:5432'
  db2:
    image: mariadb:11.5.2@sha256:4a1de8fa2a929944373d7421105500ff6f889ce90dcb883fbb2fdb070e4d427e
    volumes:
      - db2-data:/var/lib/mysql
    environment:
      MARIADB_USER: maria
      MARIADB_PASSWORD: my_cool_secret
      MARIADB_ROOT_PASSWORD: my-secret-pw
      MARIADB_DATABASE: asobiba
    ports:
      - '13306:3306'

  redis:
    image: redis:7.4.1@sha256:a06cea905344470eb49c972f3d030e22f28f632c1b4f43bbe4a26a4329dd6be5
    ports:
      - '16379:6379'
  zipkin:
    image: openzipkin/zipkin-slim@sha256:5e1b175ef3025e8996ab10b70033a67b33d5c59b5db05904026f44db8d2ba2e2
    ports:
      - 9411:9411

volumes:
  db-data:
  db2-data:
