services:
  db:
    image: postgres:16.0@sha256:1f15664bb5e0286cf5c68a26b4fdae13e3905ae632821c355b043adee2254509
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: asobiba
    ports:
      - '15432:5432'
  db2:
    image: mariadb:11.1.2@sha256:2403cc521634162f743b5179ff5b35520daf72df5d9e7e397192af685d9148fd
    volumes:
      - db2-data:/var/lib/mysql
    environment:
      MARIADB_USER: maria
      MARIADB_PASSWORD: my_cool_secret
      MARIADB_ROOT_PASSWORD: my-secret-pw
      MARIADB_DATABASE: asobiba
    ports:
      - '13306:3306'

  redis:
    image: redis:7.2.1@sha256:55f70c57c74b25d00c38ff60726da1caee17202774af2de365c36628d9b3c7e1
    ports:
      - '16379:6379'
  zipkin:
    image: openzipkin/zipkin-slim@sha256:929ef4ba52188f342716a6407b1a4537013fd7b1814ab7cde9f56ef5cc22f5f0
    ports:
      - 9411:9411

volumes:
  db-data:
  db2-data:
