/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

group = "$group.example-app"

plugins {
    id("net.yewton.asobiba.kotlin-library")
}

dependencies {
    api(project(":list"))
}
