spring:
  ai:
    model.chat: openai
    openai:
      base-url: https://generativelanguage.googleapis.com/v1beta/openai/
      chat:
        options:
          model: gemini-2.5-pro-preview-03-25
        completions-path: /chat/completions
