# https://github.com/spring-projects/spring-ai/issues/2647
spring:
  ai:
    model.chat: vertexai
    vertex:
      ai:
        gemini:
          location: us-central1
          chat:
            options:
              model: gemini-2.5-pro-preview-03-25
