[versions]
detekt = "1.23.8"
kotest = "5.9.1"
spring-doc = "2.8.13"
therapi-runtime-javadoc = "0.15.0"
resilience4j = "2.3.0"

[libraries]
archunit-junit5 = "com.tngtech.archunit:archunit-junit5:1.4.1"
# @pin 敢えてこのバージョンにするというのが意図っぽいので( see https://github.com/gradle/gradle/blob/v7.6.0/subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/internal/JvmProjectInitDescriptor.java#L214 )
commons-text = "org.apache.commons:commons-text:1.9"
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
detekt-plugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
jetbrains-annotations = "org.jetbrains:annotations:26.0.2-1"
junit-bom = "org.junit:junit-bom:5.13.4"
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-extensions-spring = "io.kotest.extensions:kotest-extensions-spring:1.3.0"
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
# https://github.com/spring-projects/spring-boot/blob/v3.4.4/gradle.properties
kotlin-bom = "org.jetbrains.kotlin:kotlin-bom:1.9.25"
node-plugin = "com.github.node-gradle:gradle-node-plugin:7.1.0"
spotless-plugin = "com.diffplug.spotless:spotless-plugin-gradle:6.25.0"
spring-boot-plugin = "org.springframework.boot:spring-boot-gradle-plugin:3.4.4"
spring-dependency-management-plugin = "io.spring.dependency-management:io.spring.dependency-management.gradle.plugin:1.1.7"
springdoc-openapi-starter-common = { module = "org.springdoc:springdoc-openapi-starter-common", version.ref = "spring-doc" }
springdoc-openapi-starter-webflux-ui = { module = "org.springdoc:springdoc-openapi-starter-webflux-ui", version.ref = "spring-doc" }
testcontainers-bom = "org.testcontainers:testcontainers-bom:1.21.3"
therapi-runtime-javadoc-core = { module = "com.github.therapi:therapi-runtime-javadoc", version.ref = "therapi-runtime-javadoc" }
therapi-runtime-javadoc-scribe = { module = "com.github.therapi:therapi-runtime-javadoc-scribe", version.ref = "therapi-runtime-javadoc" }
resilience4j-spring-boot3 = { module = "io.github.resilience4j:resilience4j-spring-boot3", version.ref = "resilience4j" }
resilience4j-reactor = { module = "io.github.resilience4j:resilience4j-reactor", version.ref = "resilience4j" }

[plugins]
version-catalog-update = "nl.littlerobots.version-catalog-update:0.8.5"
versions = "com.github.ben-manes.versions:0.53.0"
