/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Support convention plugins written in Kotlin.
    // Convention plugins are build scripts in 'src/main' that automatically become available
    // as plugins in the main build.
    `kotlin-dsl`
    id("net.yewton.asobiba.detekt")
}

dependencies {
    implementation(platform("net.yewton.asobiba.platform:plugins-platform"))

    implementation(project(":commons"))
    implementation("net.yewton.asobiba.build-logic-lint:detekt")
    implementation("org.jetbrains.kotlin:kotlin-gradle-plugin")
}
