# NOTE: You must disable the banner and the console logging
# to allow the STDIO transport to work !!!
spring:
  main:
    banner-mode: off
    web-application-type: none
  ai:
    mcp:
      server:
        name: my-weather-server
        version: 0.0.1
        stdio: true
        type: SYNC
        resource-change-notification: true
logging:
  level:
    org.spring.ai: DEBUG
    java.net.http: DEBUG
  pattern:
    console:
  file:
    name: ./logs/mcp-server.log
