
spring:
  config:
    import:
      - "optional:classpath:/secrets/properties.yml"
  web:
    resources:
      chain.strategy:
        content:
          enabled: true
          paths:
            - "assets/**"
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: FIXME
            clientSecret: FIXME
            redirectUri: "{baseUrl}/login/callback/{registrationId}"
logging:
  level:
    reactor:
      netty:
        http:
          client: DEBUG
server:
  error:
    whitelabel:
      enabled: false
resilience4j:
  circuitbreaker:
    instances:
      failure:
        registerHealthIndicator: true
        slidingWindowSize: 20
  retry:
    instances:
      failure:
        maxAttempts: 5
        waitDuration: 500ms
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    circuitbreakers:
      enabled: true
